build_environment: Ubuntu 14.04
language: node_js
sudo: required
services:
  - docker
node_js:
  - "0.10"
before_install:
  - docker pull ubuntu:latest
  - cd app
  - make install
script:
  - make test
