---
- hosts: default
  remote_user: ubuntu
  sudo: true

  tasks:
    - name: Add apt-key for docker
      command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: Add apt-repository
      command: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
    
    - name: apt-get update
      apt: update_cache=yes
    
    - name: apt policy for docker
      command: apt-cache policy docker-engine 

    - name: Instalar todos los paquetes necesarios para la aplicacion
      apt: name=curl state=present
      apt: name=build-essential state=present
      apt: name=git state=present
      apt: name=nodejs state=present
      apt: name=npm state=present
      apt: name=docker-engine state=present
      apt: name=daemon state=present

    - name: Clone Try-2-Learn
      shell: rm -r Try-2-Learn && git clone https://github.com/jesusgn90/Try-2-Learn
    
    - name: npm install
      shell: cd /home/ubuntu/Try-2-Learn && npm install

    - name: Runs docker
      shell: daemon -- docker -d 

    - name: Runs app
      shell: cd /home/ubuntu/Try-2-Learn && daemon -- nodejs bin/www 
