---
- hosts: default
  remote_user: ubuntu
  sudo: true

  tasks:
    - name: Add apt-key for docker
      command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: Add apt-repository
      shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list

    - name: apt-get update
      apt: update_cache=yes
   
    - name: apt policy for docker
      command: apt-cache policy docker-engine 

    - name: apt-get update
      apt: update_cache=yes

    - name: Instalar curl
      apt: name=curl state=present
    - name: Instalar build-essential
      apt: name=build-essential state=present
    - name: Instalar git
      apt: name=git state=present
    - name: Instalar nodejs
      apt: name=nodejs state=present
    - name: Instalar npm
      apt: name=npm state=present
    - name: Instalar docker
      apt: name=docker-engine state=present

    - name: Clone Try-2-Learn
      git: repo=https://github.com/jesusgn90/Try-2-Learn.git  dest=/home/ubuntu/Try-2-Learn

    - name: npm install
      npm: path=/home/ubuntu/Try-2-Learn

#    - name: Runs docker
#      shell: nohup docker -d &



    - name: Instalar forever (para arrancar la aplicación con NodeJS).
      npm: name=forever global=yes state=latest

    - name: Symlink nodejs -> node
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    - name: Comprobar si hay ya alguna aplicación con NodeJS
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start Try-2-Learn.
      command: forever start /home/ubuntu/Try-2-Learn/bin/www
      when: "forever_list.stdout.find('/home/ubuntu/Try-2-Learn/bin/www') == -1"

